### ISSUE TITLE
[BUG]Unable to detect the encircled due to their translucent nature

### ISSUE THREAD

**Issue by rudrapsc** [Udayraj123/OMRChecker#103]
**Describe the bug**
Most of the read responses on the terminal in sample 6 are incorrectly interpreting the roll numbers

**To Reproduce**
1. Use sample ' samples\sample6\jpg'
2.  From the command line run: 'python3 main.py -i samples/sample6.'
3. See  Read Response:   {'Roll':  '} on most of the samples.

**Expected behavior**
It should be able to read the encircled values for the roll number accurately.

**Screenshots**
 image:     samples\sample6\jpg\sample_roll_11.jpg
![error](https://user-images.githubusercontent.com/114874767/205128837-2130a93d-9577-4097-afe9-cb7265bed1c6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 -Python 3.10.7
 -OpenCV 4.6.0

**Comment by rudrapsc** [comment]
Sir, I would like to work on this issue.

**Comment by Udayraj123** [comment]
Cool. You can discuss your approach on discord before raising a PR. I am assigning this to you as part of fossoverflow.

**Comment by ManasviEmmadi** [comment]
@rudrapsc hey are you working on this issue?

**Comment by rudrapsc** [comment]
> @rudrapsc hey are you working on this issue?

hey, I already raised a PR regarding the issue.

**Comment by Gauravmauryaios** [comment]
Sir, I would like to work on this issue.working on this project.

**Comment by Udayraj123** [comment]
fixed by https://github.com/Udayraj123/OMRChecker/pull/109
