### ISSUE TITLE
[Bug] Unexpected Output(Cropping Issue) in `Template Layout` for the sample `/inputs/AdrianSamples/adrian_omr.png`

### ISSUE THREAD

**Issue by Abhay04ch** [Udayraj123/OMRChecker#104]
**Describe the bug**
While running the code of the sample example, the command `python3 main.py --setLayout` should give the cropped template layout automatically. However, the generated template layout is incorrectly cropped.

**To Reproduce**

1. Open (https://github.com/Udayraj123/OMRChecker/wiki/User-Guide) and follow the steps as per the guide.
2. After creating the file `inputs/template.json` and adding the given text to it. Run the command `python3 main.py --setLayout` on the terminal.
3. Following the above command produces an template layout improperly cropped.

**Expected behavior**
The page should have got cropped automatically and show a basic overlay of the template.

**Screenshots**

<img width="459" alt="image" src="https://user-images.githubusercontent.com/109432943/206248157-fad27fee-f233-4496-9f31-2d8e7511273f.png">

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Python 3.11.0
 - OpenCV 4.6.0

**Comment by Udayraj123** [comment]
Able to reproduce the issue. Thanks.

**Comment by Udayraj123** [comment]
I think the image in the wiki was compressed too much. I'll update it to a better quality

It works well for an uncompressed image.
<img width="356" alt="image" src="https://github.com/Udayraj123/OMRChecker/assets/16881051/d9985081-7aef-4d9d-9a1e-660bc2289d54">

**Comment by Udayraj123** [comment]
Image updated at https://raw.githubusercontent.com/wiki/Udayraj123/OMRChecker/images/AdrianSample/HE/adrian_omr.png
