### ISSUE TITLE
Error while testing OMRChecker

### ISSUE THREAD

**Issue by inglesuniversal** [Udayraj123/OMRChecker#11]
Hello:

Got this error when launching the main.py script... any ideas?

I'm running an AWS Bitnami LAMP Server which I just updated to python 3

Here is what happened:

~/OMRChecker$ python3 main.py

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    import cv2
  File "/home/bitnami/.local/lib/python3.5/site-packages/cv2/__init__.py", line 3, in <modu
le>
    from .cv2 import *
ImportError: libXrender.so.1: cannot open shared object file: No such file or directory

Best regards

**Comment by Udayraj123** [comment]
@inglesuniversal it looks like an issue with opencv setup. Can you try this in your terminal -
```
python3
> import cv2
```
If it is still giving the same error, then you may need to reinstall opencv.

**Comment by Udayraj123** [comment]
This might help - 
https://stackoverflow.com/questions/52547833/have-trouble-with-opencv-import

**Comment by inglesuniversal** [comment]
STEP 1:

~$ python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bitnami/.local/lib/python3.5/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libXrender.so.1: cannot open shared object file: No such file or directory
>>>

**Comment by inglesuniversal** [comment]
STEP 2

$ sudo apt-get install libxrender1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libxrender1
0 upgraded, 1 newly installed, 0 to remove and 76 not upgraded.
Need to get 18.5 kB of archives.
After this operation, 80.9 kB of additional disk space will be used.
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial/main amd64 libxrender1 amd64 1:0.9.9-0ubuntu1 [18.5 kB]
Fetched 18.5 kB in 0s (1,569 kB/s)
Selecting previously unselected package libxrender1:amd64.
(Reading database ... 102905 files and directories currently installed.)
Preparing to unpack .../libxrender1_1%3a0.9.9-0ubuntu1_amd64.deb ...
Unpacking libxrender1:amd64 (1:0.9.9-0ubuntu1) ...
Setting up libxrender1:amd64 (1:0.9.9-0ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...

**Comment by inglesuniversal** [comment]
STEP 3

~$ python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> 

NO ERRORS!!!! Will test again....

**Comment by inglesuniversal** [comment]
STEP 4 (running test)

~/OMRChecker$ python3 main.py
Checking Directories...
Present : outputs/CheckedOMRs/
Present : outputs/Manual/
Present : outputs/Results/
Present : outputs/Manual/MultiMarkedFiles/
Present : outputs/Manual/ErrorFiles/
Present : outputs/Manual/BadRollNosFiles/
Found marker at: inputs/omr_marker.jpg Shape: (159, 160)

Checking Files...
Present : appending to outputs/Results/Results_J_09PM.csv
Present : appending to outputs/Manual/BadRollNoFiles_J.csv
Present : appending to outputs/Manual/MultiMarkedFiles_J.csv
Present : appending to outputs/Manual/ErrorFiles_J.csv

Additional Modules:
Cropping Enabled   : True
Markers Enabled    : True
Auto Alignment     : False

Total images present    : 1

(1) Opening image:  inputs/OMR_Files/MobileCameraBased/JE/sheet1.jpg Resolution:  (1240, 930)
Found page corners:  [[728, 832], [205, 824], [197, 332], [670, 330]]
Matching Marker: Q1: maxT 0.532Q2: maxT 0.622Q3: maxT 0.777Q4: maxT 0.693Scale 0.94
: cannot connect to X server 


QUESTION: Is this the expected output?

Thanks

**Comment by udayraj-ud** [comment]
Yes, given current settings. As it is showing "(1) Opening image", it means showimglvl is a value greater than 0. Now since you are running it via ssh on a remote computer, there is no display to show the image (thus the message `: cannot connect to X server`). You can disable image showing by setting showimglvl to 0 in `globals.py` file. And after the program finishes checking, you can see the outputs/ folder to see everything the code has generated

**Comment by udayraj-ud** [comment]
Although it is recommended to set up the project on a local computer first. 
OMRChecker is pretty light weight and the mentioned speed '200 OMRs/min' is calculated on a personal laptop with 8GB ram.  Once you have done the tuning with sample images, then you can easily run it in one go on a bigger dataset on the remote machine

**Comment by inglesuniversal** [comment]
AMAZING!!!! It worked beautifully!!!

LOG...

(1) Opening image:  inputs/OMR_Files/MobileCameraBased/JE/sheet1.jpg Resolution:
  (1240, 930)
Found page corners:  [[728, 832], [205, 824], [197, 332], [670, 330]]
Matching Marker: Q1: maxT 0.532Q2: maxT 0.622Q3: maxT 0.777Q4: maxT 0.693Sca
le 0.94
Thresholding: globalTHR:  169.31 globalStdTHR:  11.22 
Saving Image to outputs/CheckedOMRs/JE/MobileCameraBased_sheet1.jpg



Now.... 
How do I create my own forms? 
Do I have to use the markers on 3 out of 4 corners?
Do I have to "train" different form types (I use one very similar to the TOEFL® ITP Exam)
and finally... Yours gives a score of 0 (zero)... Can it show or process the score without manual intervention'

Regards

**Comment by Udayraj123** [comment]
Can you please join in the discord group? It'd be convenient to discuss there https://discord.gg/qFv2Vqf

**Comment by Udayraj123** [comment]
Closing this issue as the problem mentioned in the title is resolved :)
