### ISSUE TITLE
Score is 0 is it a [Bug] or is it not implemented yet?

### ISSUE THREAD

**Issue by umarfarooqumzen** [Udayraj123/OMRChecker#114]
I have tried with every sample and all i get is score=0 for every run what is the issue, not a python guy so apologies in advance if i am being wrong about it.

**Comment by Udayraj123** [comment]
@umarfarooqumzen it's not implemented yet. Currently we let the users calculate the score using excel formulae.

@Rohan-G has discussed a generalized schema for an evaluation schema in https://github.com/Udayraj123/OMRChecker/issues/89

**Comment by Udayraj123** [comment]
Closing as duplicate of #89 
@umarfarooqumzen feel free to continue this discussion there.
