### ISSUE TITLE
[Bug]Error while running the pre-commit as the CONTRIBUTING.md

### ISSUE THREAD

**Issue by rudrapsc** [Udayraj123/OMRChecker#119]
**Describe the bug**
I installed pre-commit by commands given in CONTRIBUTING.md after installing when i tried to run pre-commit it gave process error.

**To Reproduce**
 `pip install -r requirements.dev.txt && pre-commit install`
`git .add`
 `pre-commit run --files`

**Expected behavior**
should be able to refactor the code

**Screenshots**
![image](https://user-images.githubusercontent.com/114874767/211055851-5e1f2ba3-ea55-407e-9d5f-01c5904a5e4d.png)

**Comment by Udayraj123** [comment]
Try migrating to github. Refer [this](https://stackoverflow.com/questions/74843772/pre-commit-suddenly-fails-to-install-flake8)

**Comment by rudrapsc** [comment]
![image](https://user-images.githubusercontent.com/114874767/211057574-c67513b7-1456-4da1-972a-ce85767e5598.png)

on updating .pre-commit-config.yaml
pre-commit run is working fine

**Comment by Udayraj123** [comment]
Fixed by https://github.com/Udayraj123/OMRChecker/pull/120

As pre-commit project has moved to github: https://stackoverflow.com/questions/74843772/pre-commit-suddenly-fails-to-install-flake8
