### ISSUE TITLE
[Bug] OMR input images are processed twice in windows environment

### ISSUE THREAD

**Issue by anandSTPS** [Udayraj123/OMRChecker#130]
**Describe the bug**
[Bug] OMR input images are processed twice in windows environment. Possibly because windows is case-insensitive.

**To Reproduce**
file to edit src/entry.py (the following edit solves the issue)

import platform

if(platform.system()=="Windows"):
    exts = ("*.png", "*.jpg", "*.jpeg")
else:
    exts = ("*.png", "*.jpg", "*.jpeg", "*.PNG", "*.JPG", "*.JPEG")

**Expected behavior**
OMR input files must be processed only once

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Python version 3.10.5
 - OpenCV 4.7.0

**Comment by Udayraj123** [comment]
Hi @anandSTPS, good catch! I might have missed that as macOS filesystem is case-insensitive. Better if we change the condition to be case-insensitive only

**Comment by anandSTPS** [comment]
Yes, converting all file extension names to lower or uppercase before processing will do just fine.

**Comment by Udayraj123** [comment]
@anandSTPS feel free to open a PR for the same then

**Comment by Udayraj123** [comment]
Closing as fixed in #132
