### ISSUE TITLE
Score is not displaying in output csv file

### ISSUE THREAD

**Issue by dk-dinesh07** [Udayraj123/OMRChecker#134]
final output score of a checked OMR is not displaying in the output csv file. It displays only 0 as the output in score column of a output csv file.

**Comment by Udayraj123** [comment]
@dk-dinesh07 which sample are you running it on? Only some of the samples have a evaluation.json file in which the score column should get populated.

**Comment by dk-dinesh07** [comment]
I have run sample 2 and sample 4. 
Sample 4:
While running sample 4 it generates output in the table form in command prompt and output CSV file but in the CSV file it displays 0 mark (also for right answers) for all the questions marked.
Sample 2:
For sample 2 it does not show output in command prompt but generates output CSV file with 0 marks for all questions.

**Comment by Udayraj123** [comment]
@dk-dinesh07 thanks for pointing this out. Actually for sample 4 the output is going into MultiMarkedFiles.csv because of some multi-marked answers. Score was not calculated by default for such cases, but it should be calculated as we're allowing multiple correct questions in the schema

**Comment by Udayraj123** [comment]
Fixed sample4 locally after introducing a flag `filter_out_multimarked_files` in config which will default to false.

<img width="1080" alt="image" src="https://github.com/Udayraj123/OMRChecker/assets/16881051/df8997b8-0e60-4b17-bce2-4ea2716799af">


For sample2 it seems evaluation config inside a folder was not getting detected. Fixing that as well -
<img width="907" alt="image" src="https://github.com/Udayraj123/OMRChecker/assets/16881051/09f55a4d-12c6-4f9b-be2e-6fae452c2d8c">
