### ISSUE TITLE
screeninfo raise ScreenInfoError

### ISSUE THREAD

**Issue by mo2555** [Udayraj123/OMRChecker#135]
I am trying to make a django api that takes an image and passes it to the project , it works in the locale but when I am trying to deploy it on the server this message appears , any solutions please!
File "/opt/render/project/src/.venv/lib/python3.10/site-packages/screeninfo/screeninfo.py", line 32, in get_monitors
May 21 07:56:50 AM      raise ScreenInfoError("No enumerators available")
May 21 07:56:50 AM  screeninfo.common.ScreenInfoError: No enumerators available

**Comment by Udayraj123** [comment]
@mo2555 I think on a server where there is no UI, screeninfo library must be throwing the error you mentioned. It is used for calculating the window dimensions. A solution would be to simply comment the code that uses screeninfo and provide dummy values for window dimensions.

You should also pass show_image_level = 0 in your config files.

**Comment by mo2555** [comment]
Thanks it works

**Comment by mo2555** [comment]
I need another help please, I saw the wiki about creating the template.json file , but I can not create it , can I send the image to and you help me to create it ?

**Comment by Udayraj123** [comment]
@mo2555 if you're still stuck with the issue, you can ask the same on discord and get help faster :)
