### ISSUE TITLE
[Feature] Is the current version support the "bubble" to be rectangular?

### ISSUE THREAD

**Issue by 4ar0n** [Udayraj123/OMRChecker#136]
Standard MC form are in rectangle in my country, does the current OMR support rectangle "bubble" as attached?
<img width="499" alt="Screenshot 2023-06-16 at 5 26 36 PM" src="https://github.com/Udayraj123/OMRChecker/assets/48918174/22355079-567d-4145-aa25-b50f1fbb3392">

**Comment by Udayraj123** [comment]
@4ar0n yes, by default the bubble size is rectangle only. You can modify bubbleDimensions accordingly...

**Comment by 4ar0n** [comment]
I have another question, as attached, the scanned result is blurred, which cause the marking to be in accurate, in addition, how should i set the parameter of thresholds?
thanks a lot/

![mc003](https://github.com/Udayraj123/OMRChecker/assets/48918174/a8ddf851-6450-4552-ade3-b877322afa04)

**Comment by Udayraj123** [comment]
@4ar0n you can use higher values for `pageDimensions`. Try doubling the values in there.

**Comment by Udayraj123** [comment]
Closing feature request as we already support this. @4ar0n you can still comment with any additional doubts or discuss it on discord :)
