### ISSUE TITLE
[Bug] Feature based alignment not working with sample6

### ISSUE THREAD

**Issue by shungiterock** [Udayraj123/OMRChecker#137]
**Describe the bug**
Unable to get sample6 working with template_fb_align.json 
FeatureBasedAlignment.py, line 54:
in apply_filter matches.sort(key=lambda x: x.distance, reverse=False)
TypeError: sort() got an unexpected keyword argument 'key' 

Changing line 50 to 
matches = list(np.array(matcher.match(from_descriptors, self.to_descriptors, None))),
makes it run, but yields odd results (screenshot below). 

**To Reproduce**
1. Rename template_fb_align.json to template.json
2. Use command:  python3 main.py -i .\samples\sample6 --setLayout

**Screenshots**
![image](https://github.com/Udayraj123/OMRChecker/assets/137216989/7418921b-f70c-4909-8c5d-ad5f22228777)

**Desktop:**
 - OS: Windows 10
 - Python version: 3.11.4
 - OpenCV version: 4.7.0.72

**Comment by Udayraj123** [comment]
Thanks for raising this issue. Looking into it soon!
