### ISSUE TITLE
[littleHelp] - Find a template

### ISSUE THREAD

**Issue by victorazv** [Udayraj123/OMRChecker#138]
Hey guys. First of all, I would like to congratulate the project contributors.
Guys, where can I find the empty template from example 3? I looked and didn't find it. I wanna print, fill and make some tests on it.
I apologize if it's there and I couldn't find it.

**Comment by Udayraj123** [comment]
Hi @victorazv, we do not have blank template files for the provided samples yet. Although you can create your own using a document editor and add the omr_marker files similar to provided samples.
