### ISSUE TITLE
[How] How can I create my custom answer sheet?

### ISSUE THREAD

**Issue by HeinKoZin** [Udayraj123/OMRChecker#147]
**Describe the expectation**
I want to scan my answer sheet with MCQ questions and Student's Index Number.

**Screenshots**
![KANGAROO ANSWER SHEET 2019 (2)-1](https://github.com/Udayraj123/OMRChecker/assets/28890199/537f0254-a4fb-4536-87e3-ca8970dd707d)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Windows]
 - Python version
 - OpenCV version

**Additional context**

Error Stack trace. Sample images used, etc

**Comment by Udayraj123** [comment]
You may follow the instructions in the Project Wiki here: https://github.com/Udayraj123/OMRChecker/wiki/
Feel free to reopen this issue if you face any errors
