### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by ajshojol22** [Udayraj123/OMRChecker#151]
How can I find dimension of a image and and bubble . Also the origin of a mcq block?

**Comment by SHALLSHADOWS** [comment]
take a ruler

**Comment by Udayraj123** [comment]
@ajshojol22 Without any user interface, this is currently done by a hit and try method. 
You can work faster by guessing the percentages for coordinates of the origin by setting the width to a round number like 1000px. 

Please use discord for discussing more where other folks can share their methods as well :)
