### ISSUE TITLE
pageDimensions field pixelating image too much[Bug]

### ISSUE THREAD

**Issue by vmanawat** [Udayraj123/OMRChecker#153]
I have a custom scoresheet which I would like to turn into a template but when I load the image in and use the `pageDimensions` attribute in the template.json file it distorts the image too much. 

I have also tried using the preProcessors to help me but nothing gives me a clear image of my scoresheet. I am attaching the zip file which contains the image (mobile captured) and the template.json file.

What values should I be updating in order to capture only the table in the scoresheet and what attributes will help me make the image clear?

[myScoresheets2.zip](https://github.com/Udayraj123/OMRChecker/files/12743355/myScoresheets2.zip)

I am also attaching the screenshot of the output I am currently getting when I run the following command
`python main.py -i .\inputs\myScoresheets2\ --setLayout`
![Screenshot 2023-09-27 141413](https://github.com/Udayraj123/OMRChecker/assets/109625428/7c56d4ad-78e5-46af-b709-7322e7d5abfd)

**Comment by Udayraj123** [comment]
@vmanawat what did you change finally?

**Comment by Udayraj123** [comment]
closing as main issue was completed by author
