### ISSUE TITLE
Taking the attendee's name and surname [Feature]

### ISSUE THREAD

**Issue by youzank** [Udayraj123/OMRChecker#154]
For my example, the optical form is created by a private school and I am testing this program on the templates for my project. I have succeed at all other sections of the code but unfortunately I cannot find any info about taking the attendee's name and surname as a character input. Can you help about that?

**Comment by Udayraj123** [comment]
Hello @youzank, a similar feature request was raised for OCR support in omrchecker. I'll cross link that issue here and close this one. You can share your sample images there so that someone may be helped to pick it up for contribution

**Comment by Udayraj123** [comment]
https://github.com/Udayraj123/OMRChecker/issues/99
