### ISSUE TITLE
Question: How to get coordinations?

### ISSUE THREAD

**Issue by muhammadmnorouzi** [Udayraj123/OMRChecker#157]
In order to draw some stuff on sheets, I need coordinates of the found values.
Are there any ways to handle it right now?

**Comment by Udayraj123** [comment]
Hi @muhammadmnorouzi, 
I've seen people use Paint or some image editor to get exact pixel positions. I personally use --setLayout option and do a few trials on actual images.
I hope you got your answers on the discord server. If not, please share more details and feel free to reopen.
