### ISSUE TITLE
issuer about memory

### ISSUE THREAD

**Issue by Dhruv00710** [Udayraj123/OMRChecker#160]
sir dont know how to use discord. so please how to use discord please give me information about that. and sir i have new issue 
res = cv2.matchTemplate(
          ^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 4380856 bytes in function 'cv::OutOfMemoryError'
and sir please replay me.

**Comment by Dhruv00710** [comment]
PLEASE SIR GIVE ME REPLY

**Comment by Udayraj123** [comment]
I'll be able to check into this by mid January. Currently I'm away from
laptop for some time.

**Comment by Dhruv00710** [comment]
ok sir thank you for replay me. and when you free please solve my query

**Comment by Dhruv00710** [comment]
sirji, if you are free then please solve my query about memory

**Comment by Udayraj123** [comment]
Hi @Dhruv00710,  for using discord you can simply login via browser after clicking the invite link: https://discord.gg/qFv2Vqf

Also before that, can you follow an [issue template](https://github.com/Udayraj123/OMRChecker/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=%5BBug%5D) mentioning the specs of your desktop/device such as OS/memory specs?

> **Desktop (please complete the following information):**
>  - OS: [e.g. MacOS, Linux, Windows]
>  - Python version
>  - OpenCV version

**Comment by Udayraj123** [comment]
Quoting an [SO answer](https://stackoverflow.com/a/64308458) and a [github issue](https://github.com/opencv/opencv/issues/10725):
> Try installing the 64 bit versions of Python and OpenCV, which should have enough address space, even if you end up swapping to disc

Feel free to reopen if the issue persists :)

**Comment by Dhruv00710** [comment]
sirji, i am also use Twain library and its works only 32 bit python. And Twain library is not work in 64 bit python. so my software developed in 32 python.

**Comment by Udayraj123** [comment]
I'm afraid you're on your own if it's not reproducible for me. You can maybe try commenting out the code which is throwing the above error (template matching). Try removing CropOnMarkers plugin and see if rest of the code runs fine

**Comment by Dhruv00710** [comment]
ok sir do it i remove CropOnMarkers. And old template & OMR SHEET is below. 

Template is:
{
  "pageDimensions": [
    1651,
    2335
  ],
  "bubbleDimensions": [
    32,
    32
  ],
  "preProcessors": [
    {
      "name": "CropOnMarkers",
      "options": {
        "relativePath": "omr_marker.jpg",
        "sheetToMarkerWidthRatio": 16
      }
    }
  ],
  "fieldBlocks": {
    "Roll_no": {
    "fieldType": "QTYPE_INT1",
    "origin": [
      236,
      534
    ],
    "fieldLabels": [
      "r1",
      "r2",
      "r3"
    ],
    "bubblesGap": 96.4,
    "labelsGap": 40.8
  },
  "MCQBlock1a1": {
    "fieldType": "QTYPE_MCQ5",
    "origin": [
      135,
      721
    ],
    "bubblesGap": 51.4,
    "labelsGap": 39.8,
    "fieldLabels": [
      "q1..20"
    ]
  }, 
  "MCQBlock1a2": {
    "fieldType": "QTYPE_MCQ5",
    "origin": [
      135,
      1527
    ],
    "bubblesGap": 51.4,
    "labelsGap": 39.8,
    "fieldLabels": [
      "q21..30"
    ]
  },
  "MCQBlock1a3": {
    "fieldType": "QTYPE_MCQ5",
    "origin": [
      135,
      1933
    ],
    "bubblesGap": 51.4,
    "labelsGap": 39.8,
    "fieldLabels": [
      "q31..40"
    ]
  }, 
  "MCQBlock1a4": {
    "fieldType": "QTYPE_MCQ5",
    "origin": [
      425,
      721
    ],
    "bubblesGap": 51.4,
    "labelsGap": 39.8,
    "fieldLabels": [
      "q41..60"
    ]
  },
  "MCQBlock1a5": {
    "fieldType": "QTYPE_MCQ5",
    "origin": [
      425,
      1527
    ],
    "bubblesGap": 51.4,
    "labelsGap": 39.8,
    "fieldLabels": [
      "q61..70"
    ]
  },
  "MCQBlock1a6": {
    "fieldType": "QTYPE_MCQ5",
    "origin": [
      425,
      1933
    ],
    "bubblesGap": 51.4,
    "labelsGap": 39.8,
    "fieldLabels": [
      "q71..80"
    ]
  },
  "MCQBlock1a7": {
    "fieldType": "QTYPE_MCQ5",
    "origin": [
      720,
      721
    ],
    "bubblesGap": 51.4,
    "labelsGap": 39.8,
    "fieldLabels": [
      "q81..100"
    ]
  },
  "MCQBlock1a8": {
    "fieldType": "QTYPE_MCQ5",
    "origin": [
      720,
      1527
    ],
    "bubblesGap": 51.4,
    "labelsGap": 39.8,
    "fieldLabels": [
      "q101..110"
    ]
  },
  "MCQBlock1a9": {
    "fieldType": "QTYPE_MCQ5",
    "origin": [
      720,
      1933
    ],
    "bubblesGap": 51.4,
    "labelsGap": 39.8,
    "fieldLabels": [
      "q111..120"
    ]
  }
  }
}
![001](https://github.com/Udayraj123/OMRChecker/assets/71647436/b2b08ba2-b9a2-4358-8eef-fda0046b87d1)

And my New OMRSHEET is below so what is template of my new OMRSHEET 
![001](https://github.com/Udayraj123/OMRChecker/assets/71647436/ae9cc5b7-458c-4d8e-b3aa-0b0cd46c0c99)

please sir replay earlier as possible.

**Comment by Dhruv00710** [comment]
PLEASE SIR GIVE ME REPLY

**Comment by Dhruv00710** [comment]
sirji, if you are free then please solve my query
