### ISSUE TITLE
ReadMe's images are not loading anymore

### ISSUE THREAD

**Issue by gs7vik** [Udayraj123/OMRChecker#161]
Describe the bug:
The section of   What can OMRChecker do for me? does not load input images anymore. To rectify this we can just add the images in a cloud and paste that cloud link here.
![issueOCR](https://github.com/Udayraj123/OMRChecker/assets/57762136/8e612c62-f537-4f90-998b-ae1616d44772)

![issueOCR2](https://github.com/Udayraj123/OMRChecker/assets/57762136/36d67a57-43ed-421f-96e8-7200b25bf644)

**Comment by steffinhustles** [comment]
They seem to be working fine now :)

<img width="1505" alt="image" src="https://github.com/Udayraj123/OMRChecker/assets/157079042/8a5248ab-7798-49ef-b724-d0c62fefd5a6">

**Comment by Udayraj123** [comment]
Great, it must be an issue from github CDN side. Closing now :)
