### ISSUE TITLE
Omr. or omr?[Bug]

### ISSUE THREAD

**Issue by pierre-imbaud** [Udayraj123/OMRChecker#162]
**Some help for newcomers**

New to this repo, and maybe mistaken.

I was looking for an "OMR" software; That is: Optical Music Recognition. something that would take a music sheet as input, printed or manuscript, and output the sheet as a file, like musicXml

Many hints suggest I am mistaken, and your development inputs "omrs", whatever it means, and outputs excel files.

Just a few words in the readme.md might help newcomers figure out the purpose of your development.

And please let me know if, by any chance, your script fits my expectations.

Thats all, folks

**Comment by Udayraj123** [comment]
Hi @pierre-imbaud, aye that's a valid suggestion. I should clearly point out Optical Mark Recognition for disambiguation. Will see what I can do. 
Also I think it can't directly help with the optical music recognition task :)

**Comment by benfrstr** [comment]
I would be happy to make a PR to clarify the readme.

**Comment by Udayraj123** [comment]
Hi @benfrstr , feel free to discuss and share a PR based on what you feel should be shown in the Readme.
