### ISSUE TITLE
[Bug] Template images cut off

### ISSUE THREAD

**Issue by mgrenier7** [Udayraj123/OMRChecker#163]
**Describe the bug**
I scan an image, it is fairly large (5100 x 6600 pixels) the image generated while I am trying to generate an accurate template is cut off. There are no scroll bars or any way to see the cot of section of the image so I can't verify the accuracy of the boxes which are cut off.

**Expected behavior**
I expect to be able to view then entire generated image. The below screen shot is the entire visible portion of the generated image, clearly not the entire scanned sheet and I can't see any more of it. Need scroll bars to view the entire image and it shouldn't depend on your screen resolution which it appears to as the generate image dimension change when I alter my resolution or when I make my screen portrait rather than landscape.

**Screenshots**
![template-sample](https://github.com/Udayraj123/OMRChecker/assets/10156338/041a6290-9725-438a-897f-4396eedbbf6d)

**Desktop (please complete the following information):**
 - Windows 11
 - Python 3.11.2

**Comment by Udayraj123** [comment]
Hi @mgrenier7, this is currently an intended behaviour as we need to see the debug outputs in full clarity by default. Also ideally the window should be possible to resize down -
<img width="403" alt="image" src="https://github.com/Udayraj123/OMRChecker/assets/16881051/ad05c53b-e635-45fb-8540-f7494ec8fd60">
<img width="206" alt="image" src="https://github.com/Udayraj123/OMRChecker/assets/16881051/0aaaf9cb-5cc3-4c6c-8d6f-5f69384b8251">

**Comment by Udayraj123** [comment]
You try this config.json file -
```
{
  "dimensions": {
    "display_height": 800,
    "display_width": 600
  },
  "outputs": {
    "show_image_level": 4
  }
}
```
And adjust display_width and height accordingly to avoid cut-offs.
