### ISSUE TITLE
[Feature] run with no desktop available

### ISSUE THREAD

**Issue by capnrash** [Udayraj123/OMRChecker#170]
Hello, I've been successful running OMRChecker on an Ubuntu desktop machine. But I'd like to be able to run it on a "server" where I only have ssh- (i.e. "terminal"-only) access. When try to run OMRChecker as ssh-ing to my machine, I get a "screeninfo.commonScreenInfoError: No enumerators available" error. I'm sure this is because it's running in an environment in which it can't pop open a new window, but doing so doesn't seem necessary when only running OMRChecker to scan a set of OMR sheets. Thanks!

**Comment by Udayraj123** [comment]
Hi @capnrash, 
There's one open PR which solves this too -
https://github.com/Udayraj123/OMRChecker/pull/152/files#diff-da441c87ae07cae2fecfbac1043a1390d34ad0d7df1135b0bc4a9d5800116fc1R13

Please extract the code snippet to pass dummy monitor to suppress above error. Also make sure to keep show_image_level: 0 in your config.json

**Comment by capnrash** [comment]
sounds great; thanks a bunch!

**Comment by Udayraj123** [comment]
Should be fixed by https://github.com/Udayraj123/OMRChecker/pull/152
