### ISSUE TITLE
find all question as answer for unanswered question

### ISSUE THREAD

**Issue by eabdollahian** [Udayraj123/OMRChecker#22]
I have problem. I have a sheet that when correct with this code in some question find two or more answer.
this is my answer sheet
![image](https://user-images.githubusercontent.com/9780002/83414733-3e13e500-a433-11ea-93b2-9aff1a0b1833.png)

and correction is like this
![image](https://user-images.githubusercontent.com/9780002/83414919-83381700-a433-11ea-8758-cfd23b1a43d1.png)

after 80 , correction is wrong. why?
and in log print "globalTHR:  255 	globalStdTHR:  255 	(Looks like a Xeroxed OMR)"

**Comment by tensorboy** [comment]
Hi @Udayraj123 

I have same issues, here is my picture:
![IMG-0299](https://user-images.githubusercontent.com/17189055/99296578-d7755e80-27fb-11eb-8b4c-44e1e07f8367.JPG)
template:

`{
  "Dimensions": [
    1846,
    1500
  ],
  "BubbleDimensions": [
    40,
    40
  ],
  "Options": {
    "Marker": {
      "RelativePath": "omr_marker.jpg",
      "SheetToMarkerWidthRatio": 17
    },
    "OverrideFlags":{
      "noCropping": true
    }
  },
  "Concatenations": {
    "Roll": [
      "Squad",
      "roll0",
      "roll1",
      "roll2",
      "roll3",
      "roll4",
      "roll5",
      "roll6",
      "roll7",
      "roll8"
    ],
    "q6": [
      "q6.1",
      "q6.2"
    ],
    "q7": [
      "q7.1",
      "q7.2"
    ],
    "q8": [
      "q8.1",
      "q8.2"
    ],
    "q9": [
      "q9.1",
      "q9.2"
    ],
    "q10": [
      "q10.1",
      "q10.2"
    ]
  },
  "Singles": [
    "q1",
    "q2",
    "q3",
    "q4",
    "q5",
    "q11",
    "q12",
    "q13",
    "q14",
    "q15",
    "q16",
    "q17",
    "q18",
    "q19",
    "q20",
    "q21",
    "q22"
  ],
  "QBlocks": {
    "Medium": {
      "qType": "QTYPE_MED",
      "orig": [
        208,
        205
      ],
      "bigGaps": [
        115,
        11
      ],
      "gaps": [
        59,
        46
      ],
      "qNos": [
        [
          [
            "Medium"
          ]
        ]
      ]
    },
    "Roll": {
      "qType": "QTYPE_ROLL",
      "orig": [
        261,
        210
      ],
      "bigGaps": [
        115,
        11
      ],
      "gaps": [
        58,
        46
      ],
      "qNos": [
        [
          [
            "roll0",
            "roll1",
            "roll2",
            "roll3",
            "roll4",
            "roll5",
            "roll6",
            "roll7",
            "roll8"
          ]
        ]
      ]
    },
    "Int1": {
      "qType": "QTYPE_INT",
      "orig": [
        935,
        211
      ],
      "bigGaps": [
        124,
        11
      ],
      "gaps": [
        57,
        46
      ],
      "qNos": [
        [
          [
            "q6.1",
            "q6.2"
          ],
          [
            "q7.1",
            "q7.2"
          ],
          [
            "q8.1",
            "q8.2"
          ],
          [
            "q9.1",
            "q9.2"
          ],
          [
            "q10.1",
            "q10.2"
          ]
        ]
      ]
    },
    "Mcq1": {
      "qType": "QTYPE_MCQ4",
      "orig": [
        198,
        826
      ],
      "bigGaps": [
        115,
        183
      ],
      "gaps": [
        93,
        62
      ],
      "qNos": [
        [
          [
            "q1",
            "q2",
            "q3",
            "q4",
            "q5"
          ]
        ]
      ]
    },
    "Mcq2": {
      "qType": "QTYPE_MCQ4",
      "orig": [
        833,
        830
      ],
      "bigGaps": [
        127,
        254
      ],
      "gaps": [
        71,
        61
      ],
      "qNos": [
        [
          [
            "q11",
            "q12",
            "q13",
            "q14"
          ],
          [
            "q15",
            "q16",
            "q17",
            "q18"
          ]
        ]
      ]
    },
    "Mcq3": {
      "qType": "QTYPE_MCQ4",
      "orig": [
        1481,
        830
      ],
      "bigGaps": [
        115,
        183
      ],
      "gaps": [
        73,
        61
      ],
      "qNos": [
        [
          [
            "q19",
            "q20",
            "q21",
            "q22"
          ]
        ]
      ]
    }
  }
}`

marker:
![omr_marker](https://user-images.githubusercontent.com/17189055/99296731-0be91a80-27fc-11eb-98df-ab40903ab059.jpg)
and result:
![sample5_IMG-0299](https://user-images.githubusercontent.com/17189055/99296822-38049b80-27fc-11eb-87fd-0041ae9eb9c9.JPG)

**Comment by Udayraj123** [comment]
@tensorboy I think your issue was fixed in discord group. New comers with similar issues may head on there for a solution. Closing now. Feel free to reopen if there's any pending query :)

**Comment by Udayraj123** [comment]
There's one more case when it detects a one-off bubble wrongly. Documenting it here under confidence calculation: https://github.com/Udayraj123/OMRChecker/issues/39

**Comment by Udayraj123** [comment]
Cross linking https://github.com/Udayraj123/OMRChecker/issues/102
