### ISSUE TITLE
creating exe and using with the  bunch of images 

### ISSUE THREAD

**Issue by sudarshan55** [Udayraj123/OMRChecker#28]
I created template.json and I am using it to detect the bubbles. But now I want to generate an exe file and use the code with a folder containing the multiple sheets. so how could I do this with existing code

**Comment by almutaealim** [comment]
do u wanna work on single active sheet at a time?

**Comment by Udayraj123** [comment]
Generating an exe file with a not-so-large size is still a challenge and may require porting the code. It is not currently in the scope of this project. Setting up opencv on python is a necessity as of now. You may want to consider running the code on Google Colab perhaps, with your images imported via google drive.
Closing this as `not an issue`.
Any discussions are welcome in the discord group (link in readme).
