### ISSUE TITLE
Understanding template format

### ISSUE THREAD

**Issue by tamnguyenvan** [Udayraj123/OMRChecker#29]
Dear team,
Huge thanks for this amazing project.
I'm wondering where I can find template format description in details? Sorry if I missed something. But I don't understand what `Concatenations`, `Singles` mean?

**Comment by Udayraj123** [comment]
Hi @tamnguyenvan, 
Have you checked the project wiki? There is a step by step guide on the process of making a template format -
https://github.com/Udayraj123/OMRChecker/wiki

Most of the fields will stay in the `Singles` key. The `Contatenations` key is a way to tell OMRChecker which fields to concatenate when generating the output csv e.g. for Roll number columns you may want to concatenate the fields(roll0, roll1, roll2, etc) and output it as a single column `Roll`

**Comment by tamnguyenvan** [comment]
Hi @Udayraj123 , thanks for your quick reply.
I've checked the wiki carefully. But I couldn't find any document about the concept such as `Singles`, `Contatenations`, `QBlocks`, `qType`. Did I miss something? Sorry if I was wrong.

**Comment by Udayraj123** [comment]
You're right about that. The wiki seems to have only a basic example there. Rest of it was meant to be understood by running the samples I think. If you could start a discussion over this in the [discord group](https://discord.gg/qFv2Vqf), I'd be able to help you quickly.

**Comment by tamnguyenvan** [comment]
@Udayraj123 , thanks. I just started a discussion. Please check

**Comment by udayrajMT** [comment]
closing as the query has been answered in the comments of the template json here
https://github.com/Udayraj123/OMRChecker/wiki/About-Templates
