### ISSUE TITLE
ORM HELP

### ISSUE THREAD

**Issue by suresh2k02** [Udayraj123/OMRChecker#31]
results.csv is showing only index like rollno,q1.q20 etc...i want ans along with score,key can you explain more in detail thanks.

**Comment by Udayraj123** [comment]
@suresh2k02 as discussed over discord group, there's no intended support for calculating score based on answer key. That part can be implemented using simple excel formulae. Or as you did in your case, achieved by slightly tweaking the code.

**Comment by Udayraj123** [comment]
@TarnWilliamsonInvivo yes ticks and crosses are not detected easily using the algorithm used in OMRChecker. If you have a suggestion or find a way to integrate with it, please drop an email or message :) 

Closing as original issue resolved over discord group.
