### ISSUE TITLE
[Readme] Clearer setup instructions

### ISSUE THREAD

**Issue by Udayraj123** [Udayraj123/OMRChecker#34]
As you setup OMRChecker on your own machine, mark your first contribution with the following

1. You can update the [Getting Started](https://github.com/Udayraj123/OMRChecker#getting-started) section with better instructions that makes the setup experience smoother.
2. For a start, you can create a different section for setting up on Windows/Linux, etc. Also, the `Installing missing libraries` section is confusing for macOS users as it doesn't run for them.
3. Since the setup instructions might have outdated with latest versions of dependencies, try running the project with latest ways of installing them and if it works, share here and propose to use the newer versions.

**Note:** this issue is marked with the `hacktoberfest` label. Follow `#hacktoberfest-discussions` [on Discord](https://discord.gg/ANUuzsrpVV) for further details .

**Comment by Rohan-G** [comment]
Hey, can I work on this for hacktoberfest?

**Comment by Udayraj123** [comment]
Feel free! There's more issues coming, you can start with it :)

**Comment by Udayraj123** [comment]
Please reach out on discord for any queries/help.

**Comment by Udayraj123** [comment]
@Rohan-G I have updated the description with more details, can you include them in your change as well?

**Comment by Udayraj123** [comment]
@Rohan-G mention the issue in that PR's description. Then we can close it

**Comment by bilal-aamer** [comment]
@Udayraj123 Can I address this issue as well? have some changes to-do!

**Comment by Udayraj123** [comment]
@bilal-aamer sure. Let's discuss on discord channel

**Comment by Udayraj123** [comment]
Also you can create one new issue @bilal-aamer. I will be closing this as @Rohan-G has merged a PR against this issue

**Comment by bilal-aamer** [comment]
> @bilal-aamer sure. Let's discuss on discord channel

Ok
