### ISSUE TITLE
[Get Familiar]: Improve logging

### ISSUE THREAD

**Issue by Udayraj123** [Udayraj123/OMRChecker#35]
Some ideas for logs: 

1.  Explore the code based on the logs you see.
2. Add log levels to them as part of your first contribution! 
3. If tidy readable outputs interest you, try using colorama to indicate log levels
4. You can also propose "modes" of logs: dev/user/minimal/silent

**Note:** this issue is marked with the `hacktoberfest` label. Follow `#hacktoberfest-discussions` [on Discord](https://discord.gg/ANUuzsrpVV) for further details .

**Comment by pixalquarks** [comment]
Hey, I would like to work on this

**Comment by Udayraj123** [comment]
@pixalquarks sure! have a look at the code and discuss your approach on discord with me. Then I can assign it to you :)

**Comment by Udayraj123** [comment]
<img width="831" alt="image" src="https://user-images.githubusercontent.com/16881051/193906536-b8c62140-a7ce-431f-ac90-19de4e6fa1a3.png">

Use colorama for color encoding.

**Comment by bilal-aamer** [comment]
Please state the relevent working path for 3.
@Udayraj123

**Comment by Udayraj123** [comment]
Search globally for `print("` and selectively edit above outputs from the screenshots @bilal-aamer

**Comment by pixalquarks** [comment]
> <img alt="image" width="831" src="https://user-images.githubusercontent.com/16881051/193906536-b8c62140-a7ce-431f-ac90-19de4e6fa1a3.png">
> 
> Use colorama for color encoding. Opening and closing brackets () and [] may be colored indicatively. Errors/Warnings etc also can be colored differently.

I was thinking of using rich, it directly supports logging, without using ansi tags. Plus it also has properly formatted traceback. Please look into it and lemme know if I should go with rich or stick to colorama

**Comment by bilal-aamer** [comment]
Please assign the issue to me! @Udayraj123 !

**Comment by bilal-aamer** [comment]
> > <img alt="image" width="831" src="https://user-images.githubusercontent.com/16881051/193906536-b8c62140-a7ce-431f-ac90-19de4e6fa1a3.png">
> > Use colorama for color encoding. Opening and closing brackets () and [] may be colored indicatively. Errors/Warnings etc also can be colored differently.
> 
> I was thinking of using rich, it directly supports logging, without using ansi tags. Plus it also has properly formatted traceback. Please look into it and lemme know if I should go with rich or stick to colorama

Lets go with the colorama for now as it gives a more friendly looking logs in the console @Udayraj123

**Comment by Udayraj123** [comment]
@bilal-aamer we shall evaluate them first as both seem useful. I've made this discussion here: https://discord.com/channels/590134763784896514/1025076621239140453/1026944631709126666

It seems rich will give us more valuable outputs as it also supports inbuilt log levels. @pixalquarks how about creating a sample log for above screenshot?

**Comment by Udayraj123** [comment]
> Please assign the issue to me! @Udayraj123 !
@bilal-aamer have you run the samples as we discussed? Start a discussion on discord and propose your changes in order to get assigned. 

Don't worry I can create a new ticket as this ticket seems to be broader and can be broken down into parts. especially point no. 3

**Comment by Udayraj123** [comment]
Can anyone share their PRs here? @bilal-aamer @pixalquarks
