### ISSUE TITLE
[Get Familiar][Core] Improve output image labels

### ISSUE THREAD

**Issue by Udayraj123** [Udayraj123/OMRChecker#42]
Steps
1. Follow Readme to setup and run OMRChecker
2. Set show_image_level = 4 or 5
3. Run OMRChecker on sample images
4. For each image that you see, try to add appropriate labels to each output image using cv2.putText, etc so that they are more understandable. For any queries discuss in discord.
5. You can create them in separate PRs if needed.

**Note:** this issue is marked with the `hacktoberfest` label. Follow `#hacktoberfest-discussions` [on Discord](https://discord.gg/ANUuzsrpVV) for further details .

**Comment by 05Alston** [comment]
Hey, can I try to solve this?

**Comment by Udayraj123** [comment]
sure @05Alston, you can discuss your approach or ask for any help in the discord channel. Link in description.

**Comment by Udayraj123** [comment]
Merged

**Comment by Udayraj123** [comment]
Creating a clone of this issue for further enhancements! Please feel free to pick this up again
