### ISSUE TITLE
[Get Familiar] Add schema validation for template configuration

### ISSUE THREAD

**Issue by Udayraj123** [Udayraj123/OMRChecker#43]
Right now, OMRChecker does not handle invalid template.json files. It simply tries to process the file and throws an errors.

We want to extend that an do a json schema validation for the file.

Steps:
1. Study current structure of the [Template file](https://github.com/Udayraj123/OMRChecker/wiki/User-Guide)
2. Create a json schema for the same. 
3. Use python-jsonschema or similar library to throw validation errors when the input file doesn't match with the schema.

Resources:
1. https://python-jsonschema.readthedocs.io/en/stable/ 
2. https://github.com/python-jsonschema/jsonschema
3. https://github.com/Udayraj123/OMRChecker/wiki/About-Templates
4. https://github.com/Udayraj123/OMRChecker/wiki/User-Guide

**Note:** this issue is marked with the `hacktoberfest` label. Follow `#hacktoberfest-discussions` [on Discord](https://discord.gg/ANUuzsrpVV) for further details .

**Comment by SpyzzVVarun** [comment]
Hi @Udayraj123 , should the schema be created exactly for the template file mentioned here: [Template File](https://github.com/Udayraj123/OMRChecker/wiki/User-Guide) ?

**Comment by Udayraj123** [comment]
That's correct. The same schema can also be found for all template.json files in samples folder

**Comment by SpyzzVVarun** [comment]
But the samples have additional things mentioned as well right? For eg: they all have detailed concatenations wheras this template does not give any specifications for it.

**Comment by Udayraj123** [comment]
You can create incorrect template.json files by removing some of the mandatory keys, or changing their camelCase to TitleCase for keys(in which case validation error should mention that). 
Setting 3rd dimension worked as code can run fine because it is written gracefully. Still we need the validation error to be thrown as a caution for future changes.

**Comment by SpyzzVVarun** [comment]
Have generated a draft PR, do let me know if this is what you were expecting.

**Comment by Udayraj123** [comment]
@SpyzzVVarun discussed on discord. Let me know once all changes done..

**Comment by Udayraj123** [comment]
Merged https://github.com/Udayraj123/OMRChecker/pull/60

**Comment by Udayraj123** [comment]
extended in https://github.com/Udayraj123/OMRChecker/issues/65
