### ISSUE TITLE
General Discussion/Comments (prefer discord)

### ISSUE THREAD

**Issue by Udayraj123** [Udayraj123/OMRChecker#5]
Comment here if anyone wants to discuss anything about the software

Discord link for quicker response: https://discord.gg/qFv2Vqf

**Comment by Siva2406** [comment]
Hey, when I try to run this on my local system with the sample you had in https://github.com/Udayraj123/OMRChecker/tree/master/inputs/OMR_Files_Sample/CityName/HE folder, I am getting **"Segmentation fault (core dumped)"** error.

**Comment by Siva2406** [comment]
I am looking for an automated evaluation of OMR sheets. Have attached  sample file for which I need to solve this. Don't know where to start for processing this. Is there any doc for the same?
![Original (1)](https://user-images.githubusercontent.com/22323218/61533382-5a40aa80-aa4a-11e9-849d-c4ada93c6642.jpeg)

**Comment by Udayraj123** [comment]
Hi @Siva2406,
You can check this section in the readme:
https://github.com/Udayraj123/OMRChecker/blob/master/README.md#applying-it-on-your-o

**Comment by Udayraj123** [comment]
Also, can you tell me the steps you followed/commands used to run the code?

**Comment by Siva2406** [comment]
Sure, did the setup on Ubuntu 16.04 and ran the code with sample files available the repo. Please find the code I used.

`sudo apt-get update -y
sudo apt-get upgrade -y
sudo reboot
python3 -m pip install --user --upgrade pip
wget https://bootstrap.pypa.io/get-pip.py
sudo python3 get-pip.py
python3 -m pip install --user --upgrade pip
python3 -m pip install --user opencv-python
python3 -m pip install --user opencv-contrib-python
git clone https://github.com/Udayraj123/OMRChecker
cd OMRChecker/
python3 -m pip install --user -r requirements.txt
sudo cp -r inputs/OMR_Files_Sample/ inputs/OMR_Files
python3 main.py`

**Comment by Siva2406** [comment]
Even I tried steps mentioned [here ](https://github.com/Udayraj123/OMRChecker/wiki/User-Guide)to create custom layout template. But, whatever I do, I am getting **"Segmentation fault (core dumped)"** error.

**Comment by utkarshrai2** [comment]
Hi Uday nice repo.
Could u explain the difference between gaps and bigGaps?

**Comment by andreemidio** [comment]
Hi @utkarshrai2 

Gaps is the distance of the balls to each other.
Big Gaps is the distance between the columns.
Important note : The Bubble dimensions is important when you measurement of Gaps and BigGaps

**Comment by utkarshrai2** [comment]
I want to use some custom OMR_Marker, are there any marker specific constants in the code. Because i am having some spacing issue when i am  setting the layout with a custom marker

**Comment by utkarshrai2** [comment]
> Hi @utkarshrai2
> 
> Gaps is the distance of the balls to each other.
> Big Gaps is the distance between the columns.
> Important note : The Bubble dimensions is important when you measurement of Gaps and BigGaps
But we are setting origin for each column separately, so whats the utility of bigGap

**Comment by Udayraj123** [comment]
If you could share a sample image and the marker on your forked repo, we can help you configure it

**Comment by Udayraj123** [comment]
@utkarshrai2 there are multiple ways to set the same grid layout. Biggaps help you do it in a minimal way.
Especially when the layout is a grid of small grids(Qblocks). Biggap is the gap between those Qblocks. Hope I'm clear

**Comment by vijuc895** [comment]
Hi @Udayraj123 I tried to configure the grid layout but unable to get the perfect match. Let me know if you could help
![Blank OMR Sample](https://user-images.githubusercontent.com/43551239/97781888-4031c980-1bb4-11eb-941e-051e4a2a42e8.jpeg)

**Comment by balaji-ch** [comment]
Hi Raj,
How did you create those GIFs ?

**Comment by olzenkhaw** [comment]
![IMG_2519](https://user-images.githubusercontent.com/54525041/149762098-58193542-3361-4ff5-9a9a-a81bc2522df2.JPG)
This is the omr I used to test.
`{
    "Dimensions": [
        960,
        1280
    ],
    "BubbleDimensions": [
        90,
        25
    ],
    "Concatenations": {},
    "Singles": [
		"q1",
		"q2",
		"q3",
		"q4",
		"q5",
		"q6",
		"q7",
		"q8",
		"q9",
		"q10",
		"q11",
		"q12",
		"q13",
		"q14",
		"q15",
		"q16",
		"q17",
		"q18",
		"q19",
		"q20",
		"q21",
		"q22",
		"q23",
		"q24",
		"q25",
		"q26",
		"q27",
		"q28",
		"q29",
		"q30",
		"q31",
		"q32",
		"q33",
		"q34",
		"q35",
		"q36",
		"q37",
		"q38",
		"q39",
		"q40"
    ],
    "QBlocks": {
        "MCQBlock1": {
            "qType": "QTYPE_MCQ4",
            "orig": [
                380,
                390
            ],
            "qNos": [
                [
                    [
						"q1",
						"q2",
						"q3",
						"q4",
						"q5"
					],
					[
						"q6",
						"q7",
						"q8",
						"q9",
						"q10"
                    ],
					[
						"q11",
						"q12",
						"q13",
						"q14",
						"q15"
					],
					[
						"q16",
						"q17",
						"q18",
						"q19",
						"q20"
					],
					[
						"q21",
						"q22",
						"q23",
						"q24",
						"q25"
					],
					[
						"q26",
						"q27",
						"q28",
						"q29",
						"q30"
					]					
                ]
            ],
            "gaps": [
                18,
                20
            ],
            "bigGaps": [
                0,
                54
            ]
        },
        "MCQBlock2": {
            "qType": "QTYPE_MCQ4",
            "orig": [
                572,
                390
            ],
            "qNos": [
                [
                    [
						"q31",
						"q32",
						"q33",
						"q34",
						"q35"
					],
					[
						"q36",
						"q37",
						"q38",
						"q39",
						"q40"
                    ]					
                ]
            ],
            "gaps": [
                18,
                20
            ],
            "bigGaps": [
                0,
                54
            ]
        }
    }
}`

![templatlayout](https://user-images.githubusercontent.com/54525041/149762428-14f74162-f2ef-42fa-b3c5-de255eaaa3d8.png)

Above is the template layout produced.

However, it cannot give me the answer.

**Comment by purusello** [comment]
Sorry for my english. I want know if I can use scanned images without border. When I use them I get the message "Paper boundary not found! Should you pass --noCropping flag?" If I use --noCropping, did I need the marker icon ?

Thanks

**Comment by olzenkhaw** [comment]
> 

 I have tried not to use the marker icon with --noCropping, it still work perfectly with scanned images. The scanned images must be the same size, same orientation etc...

**Comment by Udayraj123** [comment]
@purusello yes you need the `noCropping` flag. And marker icon is not necessary to use, to skip using it simply remove the "marker_path" entry from your template.json

**Comment by Udayraj123** [comment]
@balaji-ch the GIFs were created using a small script which is no more part of the codebase :)

**Comment by Udayraj123** [comment]
@vijuc895 if you are still facing the issue, head over to the Discord group for quicker help! Link is in Readme

**Comment by purusello** [comment]
> @purusello yes you need the `noCropping` flag. And marker icon is not necessary to use, to skip using it simply remove the "marker_path" entry from your template.json

If some scanned paper is distorted, why don't to use the marker to adjust, what do you think @vijuc895 ?

**Comment by Udayraj123** [comment]
For newcomers - prefer discussion [on discord](https://discord.gg/qFv2Vqf) for better response

**Comment by Udayraj123** [comment]
For contributors looking for more tasks - check [Project board](https://github.com/users/Udayraj123/projects/1/views/2) as well.

**Comment by Udayraj123** [comment]
closing as Readme reflects the norm to do discussions on discord
