### ISSUE TITLE
[DevX] Improve the developer experience by fixing minor issues

### ISSUE THREAD

**Issue by paranjay14b** [Udayraj123/OMRChecker#50]
Some minor issues I observed while running a sanity check of OMRChecker on my machine.

1. Unnecessary output folder created: `_MULTI_/stack` for sample1.
2. Spacing issue in the output `Matching Marker:	 Q1: max_t 0.451	Q2: max_t 0.582	Q3: max_t 0.692Q4: max_t 0.547	Optimal Scale: 0.46`. Also the name Q1, Q2, etc. can be changed to something more readable.
3. Output file naming: need correction in `<outputs/sample1/MobileCamera/CheckedOMRs/stack/sheet1.jpg_1_stack.jpg>`.
4. In the output of sample1 and sample4 :  'q8' is not there in excel & q11 is repeated twice.

**Comment by Udayraj123** [comment]
Noted.
