### ISSUE TITLE
[Linux] pip module not found issue on a fresh linux

### ISSUE THREAD

**Issue by asc249** [Udayraj123/OMRChecker#70]
I was facing this issue <ERROR: /usr/bin/python3: No module named pip > when running this command:
$ python3 -m pip install --user --upgrade pip

![image](https://user-images.githubusercontent.com/37124092/194005989-6cd37c62-978a-4e44-b4ce-14c20158ff68.png)

**Comment by Udayraj123** [comment]
Great! Wanted someone with linux report an issue with setup!

Can you address this by changing Readme.md?

**Comment by Udayraj123** [comment]
@asc249 can you mention the solution in the comment as well?

**Comment by asc249** [comment]
Sure,
You can resolve this issue by running the following command:
![Screenshot from 2022-10-05 13-39-49](https://user-images.githubusercontent.com/37124092/194012175-3d50736b-54db-4d53-8a49-1577a5e64c8b.png)

**Comment by Udayraj123** [comment]
Cool. Let's mention this in the readme now.

**Comment by Udayraj123** [comment]
Migrated to uv for reduced issues in cross platform
https://github.com/Udayraj123/OMRChecker/pull/242
