### ISSUE TITLE
[Readme][Beginner] Add a dynamic Contribution Section

### ISSUE THREAD

**Issue by Harsh-Kapoorr** [Udayraj123/OMRChecker#72]
I will add a section where it will show all the contributors profile image and will have a nice tagline too.
Please assign me this under Hacktoberfest.

Thanks & Regards

**Comment by Udayraj123** [comment]
There you go: https://github.com/users/Udayraj123/projects/1

**Comment by Udayraj123** [comment]
Make sure to push into same PR https://github.com/Udayraj123/OMRChecker/pull/67

**Comment by Udayraj123** [comment]
See bottom of this for reference https://github.com/python-geeks/Automation-scripts/blob/main/README.md

**Comment by Harsh-Kapoorr** [comment]
Yes I got it I will make it look good trust me!!

**Comment by bilal-aamer** [comment]
@Udayraj123 Can I be assigned to this issue as well?

**Comment by Harsh-Kapoorr** [comment]
Sorry I messed up with Branch and stuff and had to close that PR, so please check again and merge the PR if perfect

**Comment by Udayraj123** [comment]
@bilal-aamer it is already taken up.

**Comment by Udayraj123** [comment]
Merged
