### ISSUE TITLE
[Bug] `save_image_level` includes max 3 stacks(for all values>=3) when `show_image_level` is 1

### ISSUE THREAD

**Issue by infinity1729** [Udayraj123/OMRChecker#83]
**Describe the bug**
referring to the comment on issue #44 
Following undesirable action is being performed: 
- If show_image_level is 1 and any value of save_image_level which is greater than 3, the output stack would include max 3 stacks.

**To Reproduce**
1. Open `\src\defaults\config.json`
2. Line 24: Set `show_image_level=1`
3. Line 25: Set `save_image_level=5`
4. From the command line run: `python3 main.py -i samples/sample1`
5.  Visit `\outputs\MobileCamera\CheckedOMRs\stack` to see only 3 stacks (instead of expected 5 stacks).

**Screenshots**
![image](https://user-images.githubusercontent.com/52048907/194262787-8e59d977-c7cd-4f33-989f-34eeb16a974c.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Python 3.10.7

**Comment by Udayraj123** [comment]
merged first part 🎉

**Comment by Udayraj123** [comment]
@infinity1729 shall I close this issue? Maybe we can create a new one so that new people can pick it up as well

**Comment by Udayraj123** [comment]
Closing for now.
