### ISSUE TITLE
[Bug] Templates getting merged.

### ISSUE THREAD

**Issue by 05Alston** [Udayraj123/OMRChecker#86]
**Describe the bug**
When running the program for multiple sample types, the templates seem to be merged with that of the previous iteration. This causes rectangles and labels to be generated where it shouldn't be.

**To Reproduce**
1. Setup the project.
2. In `src/defaults/config.json` set the 'show_image_level' to either 4 or 5. 
3. Run the command `python main.py -i samples/`

**Expected behavior**
![image](https://user-images.githubusercontent.com/89850018/194558808-7ca97dda-4874-44c0-8d3c-c9857049724f.png)
![image](https://user-images.githubusercontent.com/89850018/194558892-23abe039-8026-4b08-a3fa-8985d9c944ad.png)
![image](https://user-images.githubusercontent.com/89850018/194559186-2a104068-f66e-4dd4-804f-8b5066ba6850.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/89850018/194559294-06826d59-d98b-421d-b90b-775c7b7f0746.png)
![image](https://user-images.githubusercontent.com/89850018/194559334-20cf9ee5-2494-43d4-a5e9-8ad5b0f66bb2.png)
![image](https://user-images.githubusercontent.com/89850018/194559433-4e4e461b-6122-4cb2-9257-e02334018fc8.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Python version: 3.10.7
 - OpenCV version: 4.6.0.66

**Additional context**
The issue arises due to use of deepmerge library. It can be fixed by modifying the function to make the merge non destructive to the base template.

**Comment by Kurtsley** [comment]
I'll give it a shot.
