### ISSUE TITLE
[Bug] changing `show_image_level` gives undesirable results 

### ISSUE THREAD

**Issue by infinity1729** [Udayraj123/OMRChecker#88]
**Describe the bug**
when `show_image_level=3`, we get 3 different stack of images (that are: Warped Sheet,Final Alignment Adjustment, Final marked bubbles). However when `show_image_level=4` we get only 2 stack of images (that are: Final Alignment Adjustment, Final marked bubbles)

**To Reproduce**
1. Open `\src\defaults\config.json`
2. Line 24: Set `show_image_level=3`
3. From the command line run: `python3 main.py -i samples/sample1`.  3 image stacks will be displayed.
4. Line 24: Set `show_image_level=4` 
5. From the command line run: `python3 main.py -i samples/sample1`.  2 image stacks will be displayed.

**Expected behavior**
For `show_image_level=4` four image stacks should be shown.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Python 3.10.7
 - OpenCV 4.6.0

**Additional context**
This issue is continuation of #44 and will expect to work on redefining images displayed for different `show_image_levels`.

**Comment by kushcoder12** [comment]
I would like to work on it.

**Comment by Udayraj123** [comment]
@kushcoder12 please discuss your approach on discord before getting assigned

**Comment by infinity1729** [comment]
@Udayraj123 I am interested to work on this, can you please assign it to me.

**Comment by Udayraj123** [comment]
@infinity1729 any updates?

**Comment by infinity1729** [comment]
Hey, I am sorry I got involved with something else. I won't be able to contribute as of now.

**Comment by Udayraj123** [comment]
Closing in favor of #44
