### ISSUE TITLE
[Feature][Core] Implement a generalised evaluation script

### ISSUE THREAD

**Issue by Udayraj123** [Udayraj123/OMRChecker#89]
**Is your feature request related to a problem? Please describe.**
Need support for a customisable marking scheme with negative marking, section-wise marking, bonus questions, etc. Answer keys may exist for a test booklet code. We can also support custom logic via eval scripts for handling any other cases.

**Describe the solution you'd like**
Basic evaluation scheme can be stored in template.json file 

**Criteria for Answer Schema:**
    - It should allow simplest way to grade +1 -0 case
    - Also for +4 -1 case, it should be of minimal effort
    - In all other cases we want users to modify 3-4 keys

**Describe alternatives you've considered**
Right now we can solve this by applying Excel formulae(link to [sample sheet](https://docs.google.com/spreadsheets/d/1Vs9ziifvtgHs0yqjRGkP1uf5R6kjUYcDtzXB-lFLOYo/edit#gid=0)) over the output results file. It works fine for simple cases which still requires knowledge about writing formulae in excel.

**Additional context**
NA

**Comment by Udayraj123** [comment]
Some links: 
- [Previous attempt for answer key object](https://github.com/Udayraj123/OMRChecker/commit/417021a4c419e4b70fa12b3c622c73b4f6243140#diff-a9dbd1120a04a7e2cf9f4dce14795594dfab25e48ee77b6469c7cabf841da1cbR101) - also supported 'streaks' of correct answers.
- [Evaluate function](https://github.com/Udayraj123/OMRChecker/blob/5487a22/main.py#L154)
- [Discord discussion](https://discord.com/channels/590134763784896514/1025076621239140453/1029761473574076546)

**Comment by Rohan-G** [comment]
Current schema for evaluation:

In the tempalte.json, we include a Solution section, with the data for each question ([qNo] : [[Answers,mark1],[Answers,mark2],['*DEFAULT*',Default_marks]]) as a general set of rules with more details as given below:

Schema flexibility: 
    
    Double digit integer                                       - { [qNo] : ['4', '04'] }  
    Double digit integer(X is provided in "emptyVal")          - { [qNo] : ['4', 'X4'] }  
    Multiple choice                                            - { [qNo] : [ ['A', 4] ] }
    Strictly Multiple correct                                  - { [qNo] : [ ['AB', 2] ] } 
    Partial Marking                                            - { [qNo] : [ ['A', 4], ['D', 1] ] } 
    Ambiguous correct                                          - { [qNo] : [ ['A', 4], ['B', 4] ] }
    Ambiguous correct(Cumulative score 2 options)              - { [qNo] : [ ['A', 4], ['B', 4], ['AB', 8] ] }
    Ambiguous correct(Cumulative score 3 options)              - { [qNo] : [ ['A', 4], ['B', 4], ['C', 2], ['AB', 8], ['BC', 6], ['AC', 6] ] }

    Negative (+4 -1)                                           - { [qNo] : [ ['A', 4], ['B', -1], ['C', -1], ['D', -1] ] }
    Negative (+4 -1)                                           - { [qNo] : [ ['A', 4], ['*DEFAULT*', -1] ] }
    Negative (+1 -0.25)                                        - { [qNo] : [ ['A', 1], ['*DEFAULT*', -0.25] ] }
    Bonus (+4 for all)                                         - { [qNo] : [ ['*DEFAULT*', 4] ] }

Note: order of concatenations is governed by "vals" array from template.json

**Comment by Udayraj123** [comment]
@Rohan-G are you available to work on this further?

**Comment by Rohan-G** [comment]
> @Rohan-G are you available to work on this further?

Yep I can continue working on this now.

**Comment by udayraj-rzp** [comment]
Note: there are many changes in the above schema. I'll be populating many examples in the existing samples as a demonstration

**Comment by Udayraj123** [comment]
Note: there are many changes in the above schema. I'll be populating many examples in the existing samples as a demonstration
