### ISSUE TITLE
Ideas/Feedback 

### ISSUE THREAD

**Issue by Udayraj123** [Udayraj123/OMRChecker#9]
Discuss any ideas or suggestions/feedbacks you have here.

**Comment by alesdev** [comment]
In my opinion would be useful:
1. Have a second chance to correct the answers;
2. Create templates with Latex;

**Comment by Udayraj123** [comment]
@alesdev Thanks for sharing these :)
For first one do you mean to say there should be a way to detect cross marks separately?

and for second one, we can have a template Latex/Word document for the user. After modification, they can input a screenshot of the template and OMRChecker should be able to detect template from the image(which is a task in one of the future [TODOs](https://github.com/Udayraj123/OMRChecker/wiki/TODOs))

**Comment by Udayraj123** [comment]
Closing as discussion [moved to discord](https://discord.gg/p6zMRd2CCR).
