### ISSUE TITLE
[Bug] Unexpected output in `Template Alignment Adjustment` for the sample `\community\Sandeep-1507/CheckedOMRs/omr-1.png`

### ISSUE THREAD

**Issue by aayushibansal2001** [Udayraj123/OMRChecker#97]
**Describe the bug**
While running the code with below configurations, the preview of `Template Alignment Adjustment` shows unexpected output. The text is not legible, which is due to incorrect spacing of the text displayed.

**To Reproduce**
1. set `"show_image_level": 3` in `src\defaults\config.json`
2. In the terminal run `python3 main.py -i samples/community/Sandeep-1507  `

**Expected behavior**
Either change the font size or update the spacing of the text displayed.
Try changing `(int(s[0] + d[0] - text_in_px[0][0]), int(s[1] - text_in_px[0][1]))` or `(rect[2] + 2, rect[0] + (box_h * 2) // 3)` in `src\utils\imgutils.py`

**Screenshots**
![image](https://user-images.githubusercontent.com/51708118/197170241-70dbe520-9480-41e1-8406-ea32195d4059.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Python 3.9.9
 - OpenCV 4.5.4

**Comment by Udayraj123** [comment]
@aayushibansal2001 update the command with path to the specific sample.

**Comment by dojutsu-user** [comment]
Hi @Udayraj123,
Taking this issue up. Can you please assign me this.

**Comment by Udayraj123** [comment]
I think the author is working on the issue already. But a discussion would help finalize an approach. Can you discuss it on discord @dojutsu-user?

**Comment by Udayraj123** [comment]
Also, if you're just starting, how about making a submission on #40 ?

**Comment by Udayraj123** [comment]
Also part of the PR that fixes https://github.com/Udayraj123/OMRChecker/issues/71

**Comment by Udayraj123** [comment]
@aayushibansal2001 any updates? Can I assign it to someone else?

**Comment by Udayraj123** [comment]
Closing stale issue. Previous attempt to improve upon: https://github.com/Udayraj123/OMRChecker/pull/122
